### ISSUE TITLE
[key2jwt]: allow PKCS8

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel-tools#97]
The key2jwt currently is only able to handle RSA private keys in PKCS1 format. Depending on the tool and version used to create a key pair, the create private key might be in PKCS8.

### Acceptance criteria

- [x] Sign JWT with private key of PKCS8 format

**Comment by HungryHowies** [comment]
I have this issue, Ubuntu22.0.4, Zitadel-v2.50.1, Cockroach-v23.

**Comment by Mohit21GoJs** [comment]
@livio-a I am facing this issue following documentation while following steps here: https://zitadel.com/docs/guides/integrate/zitadel-apis/access-zitadel-system-api

Seems like the tool is out of sync with the documentation above

**Comment by livio-a** [comment]
The documentation assumes that the openssl command creates a key in PKCS#1 format.
I guess you're using openssl v3. In that case you can pass the `-traditional` flag: `openssl genrsa -traditional -out system-user-1.pem 2048`.
We will add support for PKCS#8 shortly.
